

apiVersion: v1
kind: Pod
metadata:
  name: my-django-app
  labels:
    app: back
spec:
  containers:
  - name: django-container
    image: kimyoungwoo613/cicd-backend:1.0
    ports:
    - containerPort: 8000
    env:
    - name: MYSQL_HOST
      value: mysql-svc
    - name: MYSQL_PORT
      value: "3306"
    - name: MYSQL_DB
      value: awswiki_db
    - name: MYSQL_USER
      value: kube-user
    - name: MYSQL_PASSWORD
      value: pass123#

---

apiVersion: v1
kind: Service
metadata:
  name: my-django-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: back
