name: CI

on:
  push:
    branches:
      - main

jobs:
  build_backend:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Build Backend')
    outputs:
      TAG: ${{ steps.extract_tag.outputs.TAG }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Extract tag from commit message
        id: extract_tag
        run: |
          TAG=$(echo "${{ github.event.head_commit.message }}" | grep -oP 'Build Backend: \s*\K[\w\.]+')
          echo "Extracted tag is $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./aws-wiki-backend
          push: true
          tags: kimyoungwoo613/cicd-backend:${{ env.TAG }}

  build_frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Build Frontend')
    outputs:
      TAG: ${{ steps.extract_tag.outputs.TAG }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Extract tag from commit message
        id: extract_tag
        run: |
          TAG=$(echo "${{ github.event.head_commit.message }}" | grep -oP 'Build Frontend: \s*\K[\w\.]+')
          echo "Extracted tag is $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./aws-wiki-frontend
          push: true
          tags: kimyoungwoo613/cicd-frontend:${{ env.TAG }}
